### ISSUE TITLE
CI/CD: fix go environment is not effective when nightly build

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#514]
Install the runner first, then install the go environment, the go environment does not take effect.
Install the go environment first, then install the runner, the go environment takes effect.

Actually,  Github CICD provides an action to install go.
Maybe use the following action to install go can fix this problem.

```yaml
- name: Setup Go
  uses: actions/setup-go@v2
  with:
    go-version: ‘1.14.0’
```
